### ISSUE TITLE
Chinese translation of PostalPigeons

### ISSUE THREAD

**Issue by HaooooZhang** [AlexBrumbart/PostalPigeons#1]
hello. 
this is the Chinese translation of PostalPigeons.
https://pastebin.com/4ksnKRjn

**Comment by AlexBrumbart** [comment]
Hi, thanks for the translation.

I will try to include it in the mod and publish a new jar during the weekend.

**Comment by AlexBrumbart** [comment]
Added the translation to the data generators and uploaded a new file to Curseforge.
Thanks again for providing the translation.
